# Generated by Django 4.2.15 on 2024-08-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('travelerClass', models.CharField(choices=[('GEP', 'Global Entry PLUS'), ('SP', 'Sentri PLUS'), ('RLP', 'Ready Lane PLUS'), ('ATP', 'All traffic PLUS'), ('ESTA', 'ESTA')], max_length=4)),
            ],
        ),
    ]
